---
- name: Start Transmission
  block:
    - name: Create Transmission Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ transmission_config_directory }}"
        - "{{ transmission_download_directory }}"
        - "{{ transmission_watch_directory }}"

    - include_tasks: vpn.yml
      when:
        - transmission_vpn is true

    - include_tasks: no-vpn.yml
      when:
        - transmission_vpn is false

  when: transmission_enabled is true

- name: Stop Transmission
  block:
    - name: Stop Transmission
      community.docker.docker_container:
        name: "{{ transmission_container_name }}"
        state: absent
  when: transmission_enabled is false
