[Interface]
# Device: Gentle Elk
PrivateKey = EMnoJ8l2SaS3UyTs6zqY+mSyJd2UuzWtPAF+cVhkkk4=
Address = 10.70.48.48/32,fc00:bbbb:bbbb:bb01::7:302f/128
DNS = 100.64.0.7,8.8.8.8,127.0.0.11

[Peer]
PublicKey = NKP4jSvSDZg5HJ3JxpGYMxIYt7QzoxSFrU2F0m1ZxwA=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 103.216.220.18:3214
